### ISSUE TITLE
`await Promise.all` causes deadlock when measuring test coverage

### ISSUE THREAD

**Issue by PaulRBerg** [ejwessel/GanacheTimeTraveler#21]
Not entirely sure if the issue is related to ganache-time-tralever or [sol-coverage](https://sol-coverage.com), but I said to start here.

Say you have this in "beforeEach":

```javascript
await Promise.all(
  new Array(5).fill().map(() => {
    return traveler.advanceBlock();
  }),
);
```

Testing works fine (`truffle test`). However, when I plug sol-coverage, things stop working. The coverage process ends up in standstill, doing nothing after a test suite with the code above gets executed.

I can solve this easily by using a traditional for loop, or just listing the block advancements inline. But I wanted to flag the issue, in case you may know what's going on. I suspect that "Promise.all" batches promises differently and ganache ends up in a recursive loop somehow.

**Comment by PaulRBerg** [comment]
I assembled a repo to make it easy for you to reproduce the issue: https://github.com/PaulRBerg/sol-coverage-advance-block

**Comment by ejwessel** [comment]
@PaulRBerg thanks for identifying. I haven't seen this before. Let me investigate and I'll post back here.

**Comment by ejwessel** [comment]
I got it to increment with the following:

```javascript
    Promise.all(
      new Array(5).fill().map(async () => {
        return traveler.advanceBlock();
      }),
    );
```
I removed the `await` and placed `async` within the map.

**Comment by ejwessel** [comment]
@PaulRBerg did this work for you at all?

**Comment by PaulRBerg** [comment]
Hey @ejwessel sorry for the delay. Yeah so I made it work using a similar technique, but not by putting `async` inside, rather using a for loop. Thank you!
