### ISSUE TITLE
Clarify Medium article and Readme

### ISSUE THREAD

**Issue by ejwessel** [ejwessel/GanacheTimeTraveler#8]
For somebody who is not technical it should be very clear the value this brings. 
It's packaging the tools that allow you to move time which in turn can allow you to write more isolated test.

**Comment by brianwchou** [comment]
AdvanceBlock does not advance an existing block forward. It simply mines another block on top of the latest block. This needs to be changed in the README
From `ganache-cli` documentation:
>evm_mine : Force a block to be mined. Takes one optional parameter, which is the timestamp a block should setup as the mining time. Mines a block independent of whether or not mining is started or stopped.
